### ISSUE TITLE
Map ng4DCLaunchSites on Ng4_ProgramRevision

### ISSUE THREAD

**Issue by rajender2k** [sandeepmohan23/yfai_data_migration#10]
For Iteration 2 .. I'm stripping it

From mapping spreadsheet
ng4DCLaunchSites	Direct Customer Lauch Sites	string[32]						[Srini-4/3] If data exists, then we can circle back and discuss

**Comment by sandeepmohan23** [comment]
@rajender2k @premshankar1 The agreement/requirement from Srini and Sarma is that for any attribute for which the mapping is blank, thatattribute should be removed.  Since @rajender2k has removed this attribute, I will close this issue.
