### ISSUE TITLE
ng4_oem_platform_name:Ng4_Program mappped to yf5_GlobalPlatformCode:A9_ProgramItem,but yf5_GlobalPlatformCode dont exist on A9_ProgramItem

### ISSUE THREAD

**Issue by rajender2k** [sandeepmohan23/yfai_data_migration#11]
ng4_oem_platform_name:Ng4_Program mappped to yf5_GlobalPlatformCode:A9_ProgramItem,but yf5_GlobalPlatformCode dont exist on A9_ProgramItem

I'm stripping for iteration 2

FROM MAPPING>XML

  
  <map a="Ng4_Program" b="A9_ProgramItem">
    <attr>
      <a>ng4_oem_platform_name</a>
      <b>yf5_GlobalPlatformCode</b>
    </attr>

**Comment by sandeepmohan23** [comment]
@premshankar1 this is one of the attributes that is being mapped from Item-->Item Revision.  It is fine to strip it for iteration 2 but will have to be mapped correctly for iteration 3

**Comment by premshankar1** [comment]
Updated Conversion.xml to map from Item to Revision. Not tested yet.

**Comment by premshankar1** [comment]
Of the two attributes - ng4_ProgDescription and ng4_oem_platform_name, the former maps ok. But, ng4_oem_platform_name fails for the same root cause as https://github.com/sandeepmohan23/yfai_data_migration/issues/28. Implemented the workaround in conversion.xml

**Comment by premshankar1** [comment]
Tested OK
