### ISSUE TITLE
Program Attribute Mappings

### ISSUE THREAD

**Issue by sandeepmohan23** [sandeepmohan23/yfai_data_migration#12]
@premshankar1 we are seeing a lot of "ng4" attributes still remaining in transformed XML files for the A9_ProgramItem and A9_ProgramItemRevision objects.

I believe you had gone through to update all mappings for all classes to remove attributes that are not being mapped.  This is holding up our iteration as these XMLs cannot be imported.

Please go through all mappings for all program objects (Ng4_Program, Ng4_MasterProgram, Ng4_PWP, Ng4_Phase0) to ensure that all mappigns are correct and all attributes that  are not being mapped are removed.  we need this done ASAP as @bzentgraf and @rajender2k will have to re-transform and re-import.

**Comment by premshankar1** [comment]
ng4 attributes were removed from the XML's for iteration 2.
