### ISSUE TITLE
Ng4_DesignRevision did not convert

### ISSUE THREAD

**Issue by premshankar1** [sandeepmohan23/yfai_data_migration#13]
Original file, transformed file and the transform log are attached
[data_files.zip](https://github.com/sandeepmohan23/yfai_data_migration/files/1087139/data_files.zip)

**Comment by Siemens-PLM** [comment]
It looks like the items and revisions are all in different islands

**Comment by premshankar1** [comment]
Just to keep a record, the following files had failed with this issue:
assy_transfer:
ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_21.xml
ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_38.xml
ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_39.xml

During Pass2 Import, I had a mix of script and manual work to fix the problems with the last 2 files. Working on completing the script so manual work is not needed

**Comment by premshankar1** [comment]
The fix is ready. Tested with the failed files, and they transformed ok.
