### ISSUE TITLE
Mapping string to POM_untyped_reference (Attribute ng4SDTLead:Ng4_MasterPrgRevision is mapped to a9_ProgramLeader:A9_ProgramItemRevision)

### ISSUE THREAD

**Issue by rajender2k** [sandeepmohan23/yfai_data_migration#14]
Hi Sandeep & Prem,
I’ve imported the new transform files and going thru import errors… Found below mapping gap.

Attribute ng4SDTLead:Ng4_MasterPrgRevision is mapped to a9_ProgramLeader:A9_ProgramItemRevision in the XML.
But target a9_ProgramLeader attribute type is POM_untyped_reference.. So we can't map like a string.
    FROM MAPPING.xml

<map a="A9_ProgramItemRevision" b="A9_ProgramItemRevision">
  <attr>
    <a>ng4SDTLead</a>
    <b>a9_ProgramLeader</b>
  </attr>

When I looked into Sandeep mapping spreadsheet noticed no comments against this attribute.
If we are not sure about this mapping it’s better to strip for this iteration.

Thanks
Raj
PS:
<TcClass className="A9_ProgramItemRevision" description="" isExportable="false" isUninheritable="false" isUninstantiable="false" parentClassName="ItemRevision" sourceTemplate="autopoc">
  <TcAttribute attributeName="a9_ProgramLeader" attributeType="POM_untyped_reference" description="Program Leader" exportAsString="false" followOnExport="false" isArray="false" isCandidateKey="false" isNullsAllowed="true" isPublicRead="true" isPublicWrite="true" isTransient="false" isUnique="false" maxStringLength="0" noBackpointer="false"/>

FROM MAPPING SPREADSHEET
ng4SDTLead	Acting SDT Lead	string[100]			a9_ProgramLeader	Program Manager	UntypedReference

**Comment by premshankar1** [comment]
Conversion.xml has been updated last week to map the ng4DTLead to the user's puid from a lookup sheet. The mapping from email id to target user id is not available yet. This code is not tested yet.

**Comment by premshankar1** [comment]
Mapping code tested with dummy lookup file. Working ok.
