### ISSUE TITLE
With new UOM Script transform throwing win exceptions

### ISSUE THREAD

**Issue by rajender2k** [sandeepmohan23/yfai_data_migration#2]
After updating the mapping XML with the script for OOTB each UOMs, when transforming we are seeing an Unhandled Exception:

![unhandled_exception](https://user-images.githubusercontent.com/29313218/27049897-5b596b5e-4f76-11e7-9572-4e26cce1fdb8.png)

One of the XML's for which this error is occurring is the following:

[ALL_PIECE_ITEMS_PART_163.zip](https://github.com/sandeepmohan23/yfai_data_migration/files/1069204/ALL_PIECE_ITEMS_PART_163.zip)

**Comment by Siemens-PLM** [comment]
@rajender2k  this seems to be working fine for me... Did you provide the correct XML file?

**Comment by rajender2k** [comment]
Hi Mike
Find the EXE and SMU_MAPPER cs file
