### ISSUE TITLE
Issue#8	NG4_Program Attributes are missing

### ISSUE THREAD

**Issue by rajender2k** [sandeepmohan23/yfai_data_migration#22]

**Comment by premshankar1** [comment]
Sandeep's comment on Issue #7 i+j  should be relevant here too: 
Sarma is looking at "Model Name" attribute in TC10 ASP when he should be looking at "OEM Model Name"

**Comment by premshankar1** [comment]
8a+b: For Ng4_Program objects ng4MdlYear does not map to yf5_Model_Year. Exactly same mapping works for Ng4_MasterPrg but not for Ng4_Program. assy_transfer\ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_1.xml has examples of this issue

**Comment by premshankar1** [comment]
[ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_1.zip](https://github.com/sandeepmohan23/yfai_data_migration/files/1114006/ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_1.zip)

Here is a sample file for this issue

**Comment by premshankar1** [comment]
8a+b ng4MdlYear => yf5_Model_Year mapping works ok
