### ISSUE TITLE
Issue#9	ADP Program Attributes are not showing up in TC10 properly

### ISSUE THREAD

**Issue by rajender2k** [sandeepmohan23/yfai_data_migration#23]

**Comment by premshankar1** [comment]
This is to be mapped from item in V9 to ItemRevision in V10. Not supported in the current version of transformer utility.

**Comment by rajender2k** [comment]
ng4_startech on  Ng4_Phase0 Item is mapped to yf5_HyperionPlatformCode on ItemRev.
Transform tool can't handle map attributes from Item to Item Rev.This feature will be available in during Iteration 3.
So In Iteration 2 we stripped this attribute from mapping.

**Comment by premshankar1** [comment]
Conversion.xml has been updated and transformation is tested to be working correctly.
