### ISSUE TITLE
Issue#10	PWP Attributes are not showing up correctly

### ISSUE THREAD

**Issue by rajender2k** [sandeepmohan23/yfai_data_migration#24]

**Comment by premshankar1** [comment]
Mapping looks OK. Will look at the transformed XML and comment.

**Comment by rajender2k** [comment]
Requirement here is move attribute from ItemRev to Item,which is not supported by Transform tool.
Sandeep will ask Mike @mike-germano  for enhancement if possible.

**Comment by rajender2k** [comment]
Currently we are moving ng4OEM:Ng4_PWPRevision to yf5_OEMName:A9_ProgramItemRevision.
But as per Sarman and Srini's comments in the spredsheet YFAI wants to move compound property on A9_ProgramItemRevision class.
As compound property is not persistent object so we need to move the source class of the compound propery,but which is on an Item.

  
  <map a="A9_ProgramItemRevision" b="A9_ProgramItemRevision">
    <attribute name="ng4EWPStatus" value="null"/>
	<attribute name="ng4Product" value="null"/>
	<attr>
		<a>ng4OEM</a>
		<b>yf5_OEMName</b>
	</attr>

compound property:
   <TcCompoundPropertyRule description="used to retrieve the name of the customer for concatenation in the program's name field.--NO LONGER BEING USED" destPropertyName="yf5_OEMName_cmpd" destTypeName="A9_ProgramItemRevision" isReadOnly="false" pathToSource="REF(items_tag,A9_ProgramItem).yf5_OEMName" sourcePropertyName="yf5_OEMName" sourceTemplate="yfaiasp" sourceTypeName="A9_ProgramItem"/>

   <key id="Property{::}A9_ProgramItemRevision{::}yf5_OEMName_cmpd" locale="en_US" sourceTemplate="yfaiasp" status="Approved">OEM Name</key>

**Comment by rajender2k** [comment]
<map a="A9_ProgramItemRevision" b="A9_ProgramItemRevision">
    <attribute name="ng4EWPStatus" value="null"/>
	<attribute name="ng4Product" value="null"/>
	<attr>
		<a>ng4OEM</a>
		<b>yf5_OEMName</b>
	</attr>

compound property:
   <TcCompoundPropertyRule description="used to retrieve the name of the customer for concatenation in the program's name field.--NO LONGER BEING USED" destPropertyName="yf5_OEMName_cmpd" destTypeName="A9_ProgramItemRevision" isReadOnly="false" pathToSource="REF(items_tag,A9_ProgramItem).yf5_OEMName" sourcePropertyName="yf5_OEMName" sourceTemplate="yfaiasp" sourceTypeName="A9_ProgramItem"/>

   <key id="Property{::}A9_ProgramItemRevision{::}yf5_OEMName_cmpd" locale="en_US" sourceTemplate="yfaiasp" status="Approved">OEM Name</key>

**Comment by rajender2k** [comment]
"
  <map a="A9_ProgramItemRevision" b="A9_ProgramItemRevision">
    <attribute name="ng4EWPStatus" value="null"/>
	<attribute name="ng4Product" value="null"/>
	<attr>
		<a>ng4OEM</a>
		<b>yf5_OEMName</b>
	</attr>

compound property:
  " <TcCompoundPropertyRule description="used to retrieve the name of the customer for concatenation in the program's name field.--NO LONGER BEING USED" destPropertyName="yf5_OEMName_cmpd" destTypeName="A9_ProgramItemRevision" isReadOnly="false" pathToSource="REF(items_tag,A9_ProgramItem).yf5_OEMName" sourcePropertyName="yf5_OEMName" sourceTemplate="yfaiasp" sourceTypeName="A9_ProgramItem"/>

 "  <key id="Property{::}A9_ProgramItemRevision{::}yf5_OEMName_cmpd" locale="en_US" sourceTemplate="yfaiasp" status="Approved">OEM Name</key>

**Comment by rajender2k** [comment]
compound property:yf5_OEMName_cmpd

**Comment by premshankar1** [comment]
Here is the response from Sarma's:

> We will work with the Dev/Maintenance Team to create a Utility for this. (Please map to yf5_OEMName on the A9_ProgramItemRevision 


Conversion.xml has been updated last week as follows:

> <attr>

	<a>ng4OEM</a>
	<b>yf5_OEMName</b>
</attr>

**Comment by premshankar1** [comment]
Tested, working OK
