### ISSUE TITLE
Dynamic Participants classes are not in SYNC with spreadsheet

### ISSUE THREAD

**Issue by rajender2k** [sandeepmohan23/yfai_data_migration#26]
Hi Prem,
It seems to be Dynamic Participants classes are not updated in ConversionMaps.xml .
We have updated mappings in spreadsheet but in ConversionMaps.xml most of them are mapped to YF5_Other dynamic participant class. 

When I explained the Has Participant duplicate relation issue to Sarma and Srini  ,they mentioned only Ng4_SDTMember	class is mapped to YF5_Other.

Please refer YFAI_Teamcenter_Class_Mapping.xlsx file in the sharepoint and update the mapping XML.

Thanks
Raj

From ConversionMaps.xml 
  

  <map a="Ng4_DesignEngineerLead" b="A9_LeadDesigner"/>
  <map a="Ng4_ExtendedSDTMembers" b="YF5_Other"/>
  <map a="Ng4_Finance" b="YF5_SalesFinance"/>
  <map a="Ng4_LeadDesigner" b="A9_LeadDesigner"/>
  <map a="Ng4_Manufacturing" b="YF5_Manufacturing"/>
  <map a="Ng4_NotifiedDesignEnggLeads" b="YF5_Other"/>
  <map a="Ng4_NotifiedProgramManagers" b="YF5_Other"/>
  <map a="Ng4_ProgramManager" b="A9_ProgramManager"/>
  <map a="Ng4_Purchasing" b="YF5_Procurement"/>
  <map a="Ng4_Quality" b="YF5_Other"/>
  <map a="Ng4_SDTMember" b="YF5_Other"/>
  <map a="Ng4_SalesCommercial" b="YF5_Other"/>
  <map a="Ng4_Supplier" b="YF5_Other"/>

From Sandeep spreadsheet:
Ng4_Approver	A9_ProductEngineer
Ng4_DesignEngineerLead	A9_LeadDesigner
Ng4_ExtendedSDTMembers	A9_CrossFunctionalTeam
Ng4_Finance	A9_Estimator
Ng4_LeadDesigner	A9_LeadDesigner
Ng4_Manufacturing	YF5_Manufacturing
Ng4_NotifiedDesignEnggLeads	A9_TechnicalReviewBoard
Ng4_NotifiedProgramManagers	A9_AffectedProgramUsers
Ng4_ProgramManager	A9_ProgramManager
Ng4_Purchasing	YF5_Procurement
Ng4_Quality	A9_QualityEngineer
Ng4_SDTMember	YF5_Other
Ng4_SalesCommercial	A9_Sales
Ng4_Supplier	YF5_Procurement

**Comment by premshankar1** [comment]
Dynamic participants have been updated last week to match with the spreadsheet.
