### ISSUE TITLE
Missing Mapping:ng4_OEMCompany:Ng4_ExtDesignFrmStorage should be mapped to a9_Customer2:A9_PartCustomerInfoStorage attribute

### ISSUE THREAD

**Issue by rajender2k** [sandeepmohan23/yfai_data_migration#27]
Hi Prem,
As per Sandeep's spreadsheet ng4_OEMCompany:Ng4_ExtDesignFrmStorage should be mapped to a9_Customer2:A9_PartCustomerInfoStorage attribute.

But this attribute is  removed as per mapping XML.. Please correct it.

  <map a="Ng4_ExtDesignFrmStorage" b="A9_PartCustomerInfoStorage">
	<attribute name="ng4_OEMCompany" value="null"/>
	<attribute name="ng4_OEMNumber" value="null"/>
	<attribute name="ng4_OEMDesignNumber" value="null"/>
	<attribute name="ng4_OEMRevision" value="null"/>
	<attribute name="ng4_OEMDesignName" value="null"/>
	<attribute name="ng4_OEMEnvironment" value="null"/>
	<attribute name="ng4_OEMFileName" value="null"/>
	<attribute name="ng4_BusRelations" value="null"/>
  </map>

Thanks
Raj

**Comment by premshankar1** [comment]
Done
