### ISSUE TITLE
XML Malformed error

### ISSUE THREAD

**Issue by rajender2k** [sandeepmohan23/yfai_data_migration#3]
Below files are failing due special characters in TcXML files
We need to reexport after cleaning in the database.

1. XML_MALFORMED Error:
assy_transfer:
ALL_ASSY_ITEMS_DESIGN_27.xml
ALL_ASSY_ITEMS_DESIGN_28.xml
ALL_ASSY_ITEMS_DESIGN_37.xml
ALL_ASSY_ITEMS_DESIGN_38.xml
part_transfer:
ALL_PIECE_ITEMS_DESIGN_1.xml
ALL_PIECE_ITEMS_DESIGN_120.xml

**Comment by premshankar1** [comment]
We now have the following files with the above error:

assy_transfer:
ALL_ASSY_ITEMS_DESIGN_27.xml
ALL_ASSY_ITEMS_DESIGN_28.xml
ALL_ASSY_ITEMS_DESIGN_37.xml
ALL_ASSY_ITEMS_DESIGN_38.xml

part_transfer:
none

**Comment by rajender2k** [comment]
After cleaning special chars in db its exported fine...Need to repeat same in ITR 3
