### ISSUE TITLE
All parts are failing: object_type attribute added to A9_PartCustomerInfoStorage class after transform

### ISSUE THREAD

**Issue by rajender2k** [sandeepmohan23/yfai_data_migration#32]
Hi Prem,
In Iteration 3, I noticed object_type attribute added to A9_PartCustomerInfoStorage class after transform.
So all part files with this this entry in XML are failing.

Its a Form storage class so it shouldn't have object_type attributes.

When I looked into Iteration 2 transformed files we don't have object_type in transformed XMLs . SO not sure which change you made adding this attribute.

Example:
Iteation 3:
C:\apps\Siemens\Site_Consolidation\TEST_ITERATION_3\test_transform\Pass1\transformed\assy_transfer\ALL_ASSY_ITEMS_PART_1.xml
TGT:
  <A9_PartCustomerInfoStorage elemId="id1100" island_id="4716" lsd="2016-07-29T00:41:01Z" object_properties="0" parent_uid="RRXZ9bqQIRyNID" pid="1042" puid="RVQZ9bqQIRyNID" timestamp="ZeedpuTtIRyNID" a9_CustomerPartRevision="D" a9_Customer2="R1UlGB4kIX9j0C" a9_CustomerPartNo="10344236" yf5_CustomerPartName="CVR ASM,GMX365 CLSOUT CTR CNSL" yf5_ServiceIndicator="N" object_type="A9_PartCustomerInfoStorage" />

Iteration 2:
 ALL_ASSY_ITEMS_PART_1.xml
 <A9_PartCustomerInfoStorage elemId="id1561" island_id="4705" lsd="2016-07-29T00:41:01Z" object_properties="0" parent_uid="RRXZ9bqQIRyNID" pid="1042" puid="RVQZ9bqQIRyNID" timestamp="ZeedpuTtIRyNID" a9_CustomerPartRevision="D" a9_Customer2="B5dlzuUMIX9j0C" a9_CustomerPartNo="10344236" yf5_CustomerPartName="CVR ASM,GM" yf5_ServiceIndicator="N" />

IMPORT ERROR:
id1100    A9_PartCustomerInfoStorageRVQZ9bqQIRyNID      NEW            ERROR:[11072] Xml attribute [object_type] not found in database for [id1100:A9_PartCustomerInfoStorage] element.

**Comment by premshankar1** [comment]
Tested OK
