### ISSUE TITLE
When we are mapping Imanrelation type name to any OOTB Imanrelation type, class name should be ImanRelation and type name should the actual type name(i.e IMAN_specification) 

### ISSUE THREAD

**Issue by rajender2k** [sandeepmohan23/yfai_data_migration#33]
Hi Prem,
When are mapping Source Imanrelation type name to any OOTB Imanrelation type, 
class name should be ImanRelation and type name should the actual type name(i.e IMAN_specification) 

In ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_* XML files I noticed multiple Imanrelaton nodes are transformed to <IMAN_specification instead of <ImanRelation .

So import will fail as we don't have a Class with IMAN_specification,we have imantype with 'IMAN_specification' only.

Example:
assy_transfer\ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_32.xml
~~~~~~~~~~~
SRC:
<ImanType elemId="id510581" island_id="0" type_name="Ng4_WPRel"/>

<Ng4_WPRel elemId="id548910" fnd0RequiresDigitalSign="" island_id="2401" lsd="2015-03-31T18:44:35Z" object_properties="0" parent_uid="zFVRjM93IRyNID" pid="1438" primary_object="zFVRjM93IRyNID" puid="vsXVhuTqIRyNID" relation_type="#id510581" secondary_object="vYZVhuTqIRyNID" timestamp="vsZVhuTqIRyNID" user_data=""/>
~~~~~~~~~~~

TGT:
ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_32.xml:510682:  
<ImanType elemId="id510581" island_id="0" type_name="IMAN_specification" />
  <IMAN_specification elemId="id548910" fnd0RequiresDigitalSign="" island_id="2401" lsd="2015-03-31T18:44:35Z" object_properties="0" parent_uid="zFVRjM93IRyNID" pid="1438" primary_object="zFVRjM93IRyNID" puid="vsXVhuTqIRyNID" relation_type="#id510581" secondary_object="vYZVhuTqIRyNID" timestamp="vsZVhuTqIRyNID" user_data="" />

~~~~~~~~~~~
So you need to revisit the all the imanrelation whose target type is mapped to OOTB relations and change mappings accorndingly.

Some examples are

	Line 108:       <value a="Ng4_CntPltToPrg" b="IMAN_specification"/>
	Line 113:       <value a="Ng4_PortProgRel" b="IMAN_specification"/>
	Line 115:       <value a="Ng4_PrgToLaunchPrg" b="IMAN_specification"/>
	Line 119:       <value a="Ng4_SubProgram" b="IMAN_specification"/>
	Line 121:       <value a="Ng4_WPRel" b="IMAN_specification"/>


Below files are failing in imports,so we need to transform after mappings are updated.

ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_32_importer.log
ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_33_importer.log
ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_34_importer.log
ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_35_importer.log
ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_42_importer.log
ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_46_importer.log
ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_47_importer.log


Thanks
Raj

**Comment by premshankar1** [comment]
Tested OK
