### ISSUE TITLE
Ng4_DesignRevisionMaster does not convert

### ISSUE THREAD

**Issue by premshankar1** [sandeepmohan23/yfai_data_migration#34]
![pasted image at 2017_07_20 05_00 pm](https://user-images.githubusercontent.com/29379025/28418988-541c53a6-6d7b-11e7-9565-c8d93f8ea7c5.png)
In the attached XML file(zipped), Item, Revision and Forms appear to be in the same island, but the above does not transform.
[ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_46.zip](https://github.com/sandeepmohan23/yfai_data_migration/files/1162375/ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_46.zip)

**Comment by Siemens-PLM** [comment]
The form is in a different island than it's revision and item

**Comment by premshankar1** [comment]
Attaching the conversion log. We were able to take care of the problem by adding the following types of mappings for each Form class:
`<map a="Form" b="Form">
   <src-check if="@object_type = 'Ng4_DesignRevisionMaster'"/>
    <attribute name="object_type" value="'A9_AutoDesignRevisionMaster'"/>
  </map>`

[ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_46.xml.log.txt](https://github.com/sandeepmohan23/yfai_data_migration/files/1165197/ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_46.xml.log.txt)

**Comment by premshankar1** [comment]
Tested OK.
