### ISSUE TITLE
Need to remove ng4NULL and ng4_Job_Description attributes on NX0BookletItemRevision 

### ISSUE THREAD

**Issue by rajender2k** [sandeepmohan23/yfai_data_migration#36]
Hi Sandeep & Prem,
I've noticed NX0BookletItemRevision in the exports.
These ItemRevs have ng4NULL and ng4_Job_Description attributes ,we need to strip these attributes in the target.

Thanks
Raj

TARGET
TGT:
  <NX0BookletItemRevision acl_bits="0" active_seq="1" archive_date="" archive_info="" backup_date="" creation_date="2015-01-16T13:31:34Z" date_released="" declared_options="" ead_paragraph="" elemId="id13667" fnd0CurrentLocationCode="" fnd0InProcess="N" fnd0RevisionId="" fnd0reuseAssembly="" gde_bvr_list="" gov_classification="" has_variant_module="" ip_classification="" island_id="324" item_revision_id="A" items_tag="qWXRLyxHIRyNID" last_mod_date="2015-01-16T13:31:38Z" last_mod_user="#id155" license_list="" lsd="2015-01-16T13:31:38Z" ng4NULL="" ng4_Job_Description="" object_application="Teamcenter" object_desc="2755697_BT__1_A_CA_BMB____LINSENSCHRAUBE_FUER_THERMOPL__KUNST_PROF.model" object_name="2755697_BT__1_A_CA_BMB____LINSENSCHRAUBE_FUER_THERMOPL__KUNST_PROF.model" object_properties="0" object_type="NX0BookletItemRevision" owning_group="#id282" owning_organization="" owning_project="" owning_user="#id155" parent_uid="qWXRLyxHIRyNID" pid="1262" process_stage_list="" project_list="" puid="qWfRLyxHIRyNID" release_status_list="" revision_limit="1" revision_number="0" sequence_anchor="qaRRLyxHIRyNID" sequence_id="1" sequence_limit="3" timestamp="6mURLyxHIRyNID" used_options="" variant_expression_block="" wso_thread="" />

**Comment by premshankar1** [comment]
Implemented workaround in Conversion.xml. Tested OK.
