### ISSUE TITLE
Transfromer Throws Windows Exception

### ISSUE THREAD

**Issue by sandeepmohan23** [sandeepmohan23/yfai_data_migration#4]
When transforming some XMLs, the transformer is throwing a Windows Exception and crashes.

One of the XMLs that this is happening on is the following:

[ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_1.zip](https://github.com/sandeepmohan23/yfai_data_migration/files/1069470/ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_1.zip)

**Comment by sandeepmohan23** [comment]
@mike-germano, i've created a separate issue for this because this windows exception error was occurring PRIOR to you adding the UOM scripting, and is happening on different XMLs from that issue (issue #2 )

**Comment by Siemens-PLM** [comment]
I need to log this error better but this isn't a code issue. There's a problem with the logic:

`<attr-check  if="@yf5_MfgRegion != null and @yf5_MfgRegion.Contains(',')">
      <attribute name="yf5_MfgRegion" value="@yf5_MfgRegion.Split(',')[0]"/>
      <attribute name="yf5_LeadMfgCountry" value="@yf5_LeadMfgCountry.Split(',')[1]"/>
    </attr-check>`

It's failing at yf5_LeadMfgCountry with a value of "Legacy\\,Legacy". Not sure what is supposed to be accomplished here as it's reference two different properties.

**Comment by sandeepmohan23** [comment]
@mike-germano the mapping is as follows:

source attribute: ng4LaunchSite
source has values such as "Halewood,EU"
target attribute values should then be the following:
yf5_LeadMfgCountry = "Halewood"
yf5_MfgRegion = "EU"

yf5_MfgRegion should be set to "EU" (value after the comma)
yf5_LeadMfgCountry should be set to "Halewood" (value before the comma)

so i think in the attached xml yf5_MfgRegion = NA and yf5_LeadMfgCountry = Legacy\

**Comment by Siemens-PLM** [comment]
should be this then:

`<attr-check if="@yf5_MfgRegion != null and @yf5_MfgRegion.Contains(',')"> 
<attribute name="yf5_MfgRegion" value="@yf5_MfgRegion.Split(',')[0]"/>
<attribute name="yf5_LeadMfgCountry" value="@yf5_MfgRegion.Split(',')[1]"/> 
</attr-check>`

**Comment by sandeepmohan23** [comment]
@premshankar1 @bzentgraf @rajender2k could you guys please update the mapping accoridngly to see if it resovles the issue.

**Comment by rajender2k** [comment]
I have updated mapping xml and generated new exe.. New exe in the Machine B

**Comment by sandeepmohan23** [comment]
@rajender2k thanks!   

@premshankar1 please re-transform the XMLs that were failing to see if the windows exception issue has been resolved

**Comment by premshankar1** [comment]
Modified the logic for splitting the comma delimited string and the code is working ok now:

> 
	<attr-check if="@ng4LaunchSite != null and @ng4LaunchSite.Contains(',')"> 
		<attribute name="yf5_MfgRegion" value="@ng4LaunchSite.Split(',')[1]"/> 
		<attribute name="yf5_LeadMfgCountry" value="@ng4LaunchSite.Split(',')[0]"/> </attr-check>
