### ISSUE TITLE
Ng4_PlantFrm stubs found in export files

### ISSUE THREAD

**Issue by premshankar1** [sandeepmohan23/yfai_data_migration#43]
Example: 
assy_transfer\MISSED_ASSY_ITEMS_IN_TGT_1.xml
part_transfer\BZ_TEMP_EXPORT.xml
part_transfer\EXTRA_PIECE_ITEMS_DESIGN_8.xml

Can we avoid these stubs by modifying the closure rules? If not, what should be the mapping?

**Comment by rajender2k** [comment]
Some of the Matl Master item_ids are added in the input files.So MatlMaster items are exported and Ng4_PlantFrm stubs also exported. We need to make sure Matl Master item_ids are not in the input files.

Some of the Matl Master item/revs are wrongly attached to other objects.I've deleted  imanrelation where secondary object is Ng4_MtlMaster% and its in ACCT TABLE and its not Part Rev to MatlMaster relation.SO we should not get these stubs in sync or next exports.

We may get these issues in future iteration also when Matl Master wrongly copied.
In those cases we need to fix it by dropping corresponding relations and re-export.
