### ISSUE TITLE
Enhancement:Update island_ids for Item Rev related objects like Anchor

### ISSUE THREAD

**Issue by rajender2k** [sandeepmohan23/yfai_data_migration#46]
Hi Prem,
When we are replacing ItemRev island_id with Item island_id,we need to replace islands for Item Rev related reference object also..

EXAMPLE:

------- Processing island 2781 -------
ElemId    ClassName           Uid                 Status         Comments
id87287   A9_AutoDesignRevisionn PSlmFt_IRyNID      NEW            ERROR:[11072] Xml attribute [sequence_anchor = nPUlmFt_IRyNID] not found in database for [id87287:A9_AutoDesignRevision] element.
NOTE: Island import failed. All changes in this island will be rolled back.

puid="nPUlmFt_IRyNID" island_id="9960" change to island_id="2781"

 <Anchor acl_bits="0" archive_date="" archive_info="" backup_date="" creation_date="2017-07-12T15:13:16Z" elemId="id87279" immune_objects="" island_id="9960" keep_limit="1" last_mod_date="2017-07-12T15:13:16Z" last_mod_user="#id71717" lsd="2017-07-12T15:13:16Z" managed_objects="" object_properties="0" owning_group="#id264" owning_user="#id71717" parent_uid="nPSlmFt_IRyNID" pid="520" puid="nPUlmFt_IRyNID" timestamp="nPXlmFt_IRyNID" />

==================
In above exmaple, ItemRev will have sequence_anchor attribute.. sequence_anchor is typref of <Anchor

If we change the island for item rev we need to change island for related to sequence_anchor (<Anchor) also. Otherwise Item Rev load will fail..

I will come up with all the known scenarios,so you need to update replace_island.pl file.

Thx
Raj

**Comment by premshankar1** [comment]
@rajender2k do you have some example files for thi issue? Also, are there any other scenarios?

**Comment by premshankar1** [comment]
Perl code has been modified to fix this issue.
