### ISSUE TITLE
Windows Unhandled Exception

### ISSUE THREAD

**Issue by premshankar1** [sandeepmohan23/yfai_data_migration#5]
18 files in part_transfer and 1 file in assy_transfer failed with the following error on the command prompt:
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Program.Lookup(String name, String key)
   at Program.Main(String[] args)

Attaching a sample file and log file
[Unhandled_exception.zip](https://github.com/sandeepmohan23/yfai_data_migration/files/1070777/Unhandled_exception.zip)

**Comment by premshankar1** [comment]
The failed files are:
assy_transfer:
ALL_ASSY_ITEMS_DESIGN_8.xml

part_transfer:
ALL_PIECE_ITEMS_DESIGN_109.xml
ALL_PIECE_ITEMS_DESIGN_110.xml
ALL_PIECE_ITEMS_DESIGN_116.xml
ALL_PIECE_ITEMS_DESIGN_117.xml
ALL_PIECE_ITEMS_DESIGN_118.xml
ALL_PIECE_ITEMS_DESIGN_26.xml
ALL_PIECE_ITEMS_DESIGN_40.xml
ALL_PIECE_ITEMS_DESIGN_43.xml
ALL_PIECE_ITEMS_DESIGN_44.xml
ALL_PIECE_ITEMS_DESIGN_45.xml
ALL_PIECE_ITEMS_DESIGN_46.xml
ALL_PIECE_ITEMS_DESIGN_48.xml
ALL_PIECE_ITEMS_DESIGN_50.xml
ALL_PIECE_ITEMS_DESIGN_58.xml
ALL_PIECE_ITEMS_DESIGN_62.xml
ALL_PIECE_ITEMS_DESIGN_71.xml
ALL_PIECE_ITEMS_DESIGN_82.xml
ALL_PIECE_ITEMS_DESIGN_95.xml

**Comment by Siemens-PLM** [comment]
This should be corrected now. You were passing the value of a property that didn't exist as a key, so the key was null causing the failure.

This should be avoided in the future by changing the logical order of the mappings or doing a null check before changing the attribute value.
