### ISSUE TITLE
yf5_CADRequired takes 4 chars only,value=False can't make it

### ISSUE THREAD

**Issue by rajender2k** [sandeepmohan23/yfai_data_migration#9]
ng4_IsDesignRequired on Ng4_PartRevision is mapped to yf5_CADRequired on A9_autoproductRevision.

But in target yf5_CADRequired  max length is 4 char.. We need to truncate to 4 char for this iteration.
Need decision for next iteration.

Mapping:
  
  <map a="Ng4_Part" b="A9_autoproduct">

  
  <map a="A9_autoproductRevision" b="A9_autoproductRevision">

    <attr>
      <a>ng4_IsDesignRequired</a>
      <b>yf5_CADRequired</b>
    </attr>

E.g.
~~~~~~~~~~~~
SRC:
C:\apps\Siemens\Site_Consolidation\TEST_ITERATION_2\test_export\assy_transfer\ALL_ASSY_ITEMS_PART_265.xml


<Ng4_PartRevision acl_bits="0" active_seq="1" archive_date="" archive_info="" backup_date="" creation_date="2016-11-08T15:39:40Z" date_released="2016-11-30T17:28:32Z" declared_options="" ead_paragraph="" elemId="id9436" fnd0CurrentLocationCode="" fnd0InProcess="N" fnd0RevisionId="" fnd0reuseAssembly="" gde_bvr_list="" gov_classification="" has_variant_module="" ip_classification="" island_id="1710" item_revision_id="5" items_tag="1KdNUh6kIRyNID" last_mod_date="2016-11-30T17:28:59Z" last_mod_user="#id41" license_list="" lsd="2016-11-30T17:31:13Z" ng4NULL="" ng4_Assembly="" ng4_CPP_STD="Non-CPP/STD" ng4_CrossCar="" ng4_DriveConfig="" ng4_DriveTrain="" ng4_EPIC_sync_activity="" ng4_EngNetWeight="1.1990000000000000657252" ng4_EngWeightUOM="KG" ng4_ForeAft_1="" ng4_HasActiveDA="false" ng4_IsDesignRequired="False" ng4_Job_Description="" ng4_LegacyChange="" ng4_LegacyCreDate="" ng4_LegacyEffectiv="Production" ng4_LegacyModDate="" ng4_LegacyRelDate="" ng4_LegacyState="" ng4_Material="ASSEMBLY" ng4_OccPosition="" ng4_Options="" ng4_OverlayIcon="+" ng4_OwningSystem="TC" ng4_PartOriginPrgm="" ng4_PartOwner="" ng4_ProdConfig="" ng4_RelPos="" ng4_Row="" ng4_SurfaceArea="" ng4_SurfaceAreaUOM="" ng4_Treatment1="" ng4_Treatment2="" ng4_UpDown="" ng4_isSelforMajorRev="" ng4_life_cycle_state="" object_application="Teamcenter" object_desc="MD TRAEGER KARTENTASCHE TPO VTL   MD CARRIER MAP POCKET TPO FDL" object_name="MD TRAEGER KARTENTASCHE TPO VTL   MD CARRIER MAP POCKET TPO FDL" object_properties="0" object_type="Ng4_PartRevision" owning_group="#id35" owning_organization="" owning_project="#id71"  owning_user="#id40" parent_uid="1KdNUh6kIRyNID" pid="1014" process_stage_list="" project_list="#id69,#id71" puid="OtShSg52IRyNID" release_status_list="l0WhzD$2IRyNID" revision_limit="1" revision_number="0" sequence_anchor="OtUhSg52IRyNID" sequence_id="4" sequence_limit="1" structure_revisions="O5XhSg52IRyNID" timestamp="JyUhzD$2IRyNID" used_options="" variant_expression_block="" wso_thread=""/>
~~~~~~~~~~~~
TGT:
C:\apps\Siemens\Site_Consolidation\TEST_ITERATION_2\test_transform\Pass2\transformed_clean\assy_transfer\ALL_ASSY_ITEMS_PART_265.xml
    <A9_autoproductRevision acl_bits="0" active_seq="1" archive_date="" archive_info="" backup_date="" creation_date="2016-11-08T15:39:40Z" date_released="2016-11-30T17:28:32Z" declared_options="" ead_paragraph="" elemId="id9436" fnd0CurrentLocationCode="" fnd0InProcess="N" fnd0RevisionId="" fnd0reuseAssembly="" gde_bvr_list="" gov_classification="" has_variant_module="" ip_classification="" island_id="1710" item_revision_id="5" items_tag="1KdNUh6kIRyNID" last_mod_date="2016-11-30T17:28:59Z" last_mod_user="#id41" license_list="" lsd="2016-11-30T17:31:13Z" object_application="Teamcenter" object_desc="MD TRAEGER KARTENTASCHE TPO VTL   MD CARRIER MAP POCKET TPO FDL" object_name="MD TRAEGER KARTENTASCHE TPO VTL   MD CARRIER MAP POCKET TPO FDL" object_properties="0" object_type="A9_autoproductRevision" owning_group="#id35" owning_organization="" owning_project="#id71" owning_user="#id40" parent_uid="1KdNUh6kIRyNID" pid="1014" process_stage_list="" project_list="#id69,#id71" puid="OtShSg52IRyNID" release_status_list="l0WhzD$2IRyNID" revision_limit="1" revision_number="0" sequence_anchor="OtUhSg52IRyNID" sequence_id="4" sequence_limit="1" structure_revisions="O5XhSg52IRyNID" timestamp="JyUhzD$2IRyNID" used_options="" variant_expression_block="" wso_thread="" a9_weight="1.1990000000000000657252" a9_weightunit="KG" yf5_SurfaceAreaUOM="" a9_PartType="Non-CPP/STD" yf5_CADRequired="False" yf5_LegacyChange="" yf5_LegacyRelDate="" a9_LeadProgram="" />
~~~~~~~~~~~~

**Comment by sandeepmohan23** [comment]
@rajender2k @premshankar1 the target attribute yf5_CadRequired is of size 4 because it has an LOV attached to it that has values of "yes" or "no".

@premshankar1 for iteration 3, could you please update the mappings such that
if source value = true then target = yes
if source value = false then target = no

**Comment by premshankar1** [comment]
Will include in the xml for iteration 3

**Comment by rajender2k** [comment]
Hi Prem,
It seems to be you are not updated mapping XML with fixes for all the mapping issues we noticed in Iteration 2.
Please go thru all the open mapping issues and update mapping XML accordingly.

Thx
Raj

**Comment by premshankar1** [comment]
Updated Conversion.xml. Not tested yet

**Comment by premshankar1** [comment]
Testing successful. However, found instances where the source value is 'false' and 'False'. Modified the code to take care of both.

**Comment by premshankar1** [comment]
Tested OK

**Comment by premshankar1** [comment]
In the newly exported files, I am seeing values of type ng4_IsDesignRequired="Yes". We had mapped "true"/"True" => "yes". In the target system it will go as "Yes". Will it be an issue?

Example file: C:\apps\Siemens\Site_Consolidation\TEST_ITERATION_3\test_export\assy_transfer\ALL_ASSY_ITEMS_PART_1.xml

**Comment by sandeepmohan23** [comment]
@premshankar1 are you referring to the difference in lowercase vs mixed case?  We would want the value to match what is in the LOV.  In the target system the Lov is "Yes" and "No" (mixed case), so we would want the values from the source transformed accodingly.
